import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { Input } from '@components/Input';

const Home: NextPage = () => {
  const [value, setValue] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Input value={value} onChange={setValue} />
      </main>
    </div>
  );
};

export default Home;
